force-app/main/default/objects/CacheSetting__mdt/CacheSetting__mdt.object-meta.xml
<CustomObject>
    <description>Settings that map caches to implementation</description>
    <label>Cache Setting</label>
    <pluralLabel>Cache Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CacheSetting__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>The name of the class which implements the ICache interface that this setting should map to</description>
    <inlineHelpText>The name of the class which implements the ICache interface that this setting should map to</inlineHelpText>
    <label>Class Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/CacheManager.cls
/**
 * @File Name          : CacheManager.cls
 * @Description        : Entry point for interacting with various caching mechanisms
 * @Author             : Thomas Wilkins
 * @Group              : 
 * @Last Modified By   : Thomas Wilkins
 * @Last Modified On   : 3/28/2020, 12:20:01 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    3/27/2020   Thomas Wilkins     Initial Version
**/
public inherited sharing class CacheManager {
    
    @TestVisible
    private DatabaseConnection conn;
    @TestVisible
    private static Map<String, ICache> caches;

    public CacheManager(DatabaseConnection conn) {
        this.conn = conn;
    }

    public Object get(String cacheName, String key) {
        ICache cache = this.loadCache(cacheName);
        return cache.get(key);
    }

    public void set(String cacheName, String key, Object value) {
        ICache cache = this.loadCache(cacheName);
        cache.put(key, value);
    }

    private ICache loadCache(String cacheName) {
        if (caches == null) {
            caches = new Map<String, ICache>();
            List<CacheSetting__mdt> settings = (List<CacheSetting__mdt>)this.conn.query(new CacheQueryOptionsBuilder(cacheName));
            for (CacheSetting__mdt setting : settings) {
                caches.put(setting.DeveloperName.toLowerCase(), (ICache)Type.forName(setting.ClassName__c).newInstance());
            }
        }
        String cacheNameLower = cacheName.toLowerCase();
        if (!caches.containsKey(cacheNameLower)) throw new CacheException('TODO');
        return caches.get(cacheNameLower);
    }
}