force-app/main/default/objects/CacheSetting__mdt/CacheSetting__mdt.object-meta.xml
<CustomObject>
    <description>Settings that map caches to implementation</description>
    <label>Cache Setting</label>
    <pluralLabel>Cache Settings</pluralLabel>
</CustomObject>

force-app/main/default/objects/CacheSetting__mdt/fields/ClassName__c.field-meta.xml
<CustomField>
    <fullName>ClassName__c</fullName>
    <description>The name of the class which implements the ICache interface that this setting should map to</description>
    <inlineHelpText>The name of the class which implements the ICache interface that this setting should map to</inlineHelpText>
    <label>Class Name</label>
    <length>50</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/CacheSetting__mdt/fields/IsActive__c.field-meta.xml
<CustomField>
    <fullName>IsActive__c</fullName>
    <defaultValue>false</defaultValue>
    <description>Whether or not the cache is active</description>
    <inlineHelpText>Whether or not the cache is active</inlineHelpText>
    <label>Is Active</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/classes/CacheSettingsSelector.cls
/**
 * @File Name          : CacheSettingsSelector.cls
 * @Description        : Selector for caching settings
 * @Author             : Thomas Wilkins
 * @Group              : 
 * @Last Modified By   : Thomas Wilkins
 * @Last Modified On   : 3/28/2020, 12:11:16 PM
 * @Modification Log   : 
 * Ver       Date            Author      		    Modification
 * 1.0    3/28/2020   Thomas Wilkins     Initial Version
**/
public inherited sharing class CacheSettingsSelector implements ISelector {
    public Schema.SObjectType getSObjectType() {
        return CacheSetting__mdt.getSObjectType();
    }

    public List<Schema.SObjectField> getSObjectFields() {
        return new List<Schema.SObjectField> {
            CacheSetting__mdt.DeveloperName, 
            CacheSetting__mdt.ClassName__c, 
            CacheSetting__mdt.IsActive__c
        };
    }
}